In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])

In [ ]:
x[2]

3

In [ ]:
#lấy từ 1 đến 3
x[0:3]

array([1, 2, 3])

In [ ]:
#lấy từ 3 đến 8
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [ ]:
#lấy 7 và 8
x[6:8]

array([7, 8])

In [ ]:
#lấy phần từ index 2 và 4
x[2], x[4]

(3, 5)

In [ ]:
data= [(1,2), (3,4), (5,6)]
mang= np.array(data)
print(mang)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
mang[0,1] #lấy số 2

2

In [ ]:
#lấy 3 4 5 6
mang[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
#lấy 1 3 5
mang[:,0]

array([1, 3, 5])

In [ ]:
#lấy 1 và 5 theo fomat start :end:step
mang[::2,0]

array([1, 5])

In [ ]:
data=[(1,2,3,4), (5,6,7,8), (9,10,11,12), (13,14,15,16)]
mang = np.array(data)
print(mang)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#lấy 2 6 10 14 # : lấy hết hàng, lấy cột
mang[:,1]

array([ 2,  6, 10, 14])

In [ ]:
#lấy 7 11
mang[1:3,2]

array([ 7, 11])

In [ ]:
#lấy 4 7 10
mang[(0,1,2),(3,2,1)]# 012 là hàng 1->3; 321 là vị trí số

array([ 4,  7, 10])

In [ ]:
mang[3,::-1]

array([16, 15, 14, 13])

In [ ]:
data=[(1,2,3), (4,5,6), (7,8,9)]
mang = np.array(data)
print(mang)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
mang[1,:] #456

array([4, 5, 6])

In [ ]:
mang[0:2,1] #lấy 25

array([2, 5])

In [ ]:
mang[(0,1),(2,0)] #lay 3 4

array([3, 4])

In [ ]:
mang[::-1,2] #lay 9 6 3

array([9, 6, 3])

In [ ]:
data=(1,2,3,4,5,6,7,8,9,10)
mang=np.array(data)
print(mang)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
mang=[num for num in mang if num % 2 == 0] #lấy số chẵn
print(mang)

[2, 4, 6, 8, 10]


In [ ]:
data=[(1,2,3), (1,2,3), (1,2,3)]
mang = np.array(data)
print(mang)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
y= np.arange(3)


In [ ]:
y

array([0, 1, 2])

In [ ]:
data = np.random.uniform(0,10,(150,5))
data.shape

(150, 5)

In [ ]:
X = data[:, :-1]  # Lấy 4 cột đầu tiên
y = data[:, -1]  # Lấy cột cuối cùng

print(X.shape, y.shape)

(150, 4) (150,)


In [ ]:
dataset_size = X.shape[0]
dataset_size

150

In [ ]:
train_size= int (0.7* dataset_size)
train_size

105

In [ ]:
X_train = X [:train_size]
X_test=X[train_size:]

X_train.shape, X_test.shape

((105, 4), (45, 4))

In [ ]:
split = X_train.shape[0]//10
split

10

In [ ]:
for counter in range(0, X_train.shape[0], split):
    print(X_train[counter:counter+split].shape)


(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(5, 4)


#Input:
- Dữ liệu tạo mãng numpy kích thước 150 x 5
- Dữ liệu biễn x, y:
    X = data[:, :-1]  # Lấy 4 cột đầu tiên
    y = data[:, -1]  # Lấy cột cuối cùng
#Output:
- Bốn cột đầu tiên, X: (150,4)
- Cột cuối cùng, y: (150,)
- X_train.shape: (105,4); X_test.shape: (45,4)